export const QUIZ_IMAGE = require('../assets/images/quiz.PNG')
export const SPORTS_IMAGE = require('../assets/images/sports.PNG')
export const WEATHER_IMAGE = require('../assets/images/weather.PNG')
export const TICTACTOE_IMAGE = require('../assets/images/tictactoe.PNG')
export const CALCULATOR_IMAGE = require('../assets/images/calculator.PNG')
